---
- name: Ensure configuration directories exist.
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ php_conf_path }}"
    - "{{ php_cli_conf_path }}"
    - "{{ php_extension_conf_path }}"

- name: Place PHP configuration files in place.
  template:
    src: php.ini.j2
    dest: "{{ item.path }}/{{ item.filename }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { path: "{{ php_conf_path }}", filename: "{{ php_conf_filename }}" }
    - { path: "{{ php_cli_conf_path }}", filename: "{{ php_cli_conf_filename }}", cli: yes }
  notify: restart webserver
  when: php_use_managed_ini

- name: Place APC configuration file in place.
  template:
    src: apc.ini.j2
    dest: "{{ php_extension_conf_path }}/{{ php_apc_conf_filename }}"
    owner: root
    group: root
    force: yes
    mode: 0644
  when: php_enable_apc
  notify: restart webserver

- name: Ensure php-fpm is started and enabled at boot (if configured).
  service:
    name: "{{ php_fpm_daemon }}"
    state: started
    enabled: yes
  when: php_enable_php_fpm
