#$HOSTNAME = "ansible.role.php.dev"
$VM_BOX = ENV.has_key?('VM_BOX') ? ENV['VM_BOX'] : 'puphpet/debian75-x64'
#$IP = "199.199.199.13"

Vagrant.configure('2') do |config|
#  config.vm.hostname = $HOSTNAME
  config.vm.box = $VM_BOX
#  config.vm.network :private_network, ip: $IP

  config.vm.provision :ansible do |ansible|
    ansible.playbook   = 'test-vagrant.yml'
    ansible.extra_vars = {
        ansible_ssh_user: 'vagrant',
        vagrant: true
    }

    ansible.verbose = 'vvvv'

#    ansible.sudo = true
#    ansible.playbook = "test-vagrant.yml"
#    ansible.limit = "vagrant"
#    ansible.inventory_path = "inventory"
#    ansible.verbose = "vvvv"
  end
end
